//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oop2.Hrms.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public EmployeeInfo()
        {
            this.EmployeeSalaries = new HashSet<EmployeeSalary>();
            this.PaySlips = new HashSet<PaySlip>();
        }
    
        public int ID { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int DeptID { get; set; }
        public int DesiID { get; set; }
    
        public virtual DeptInfo DeptInfo { get; set; }
        public virtual DesiInfo DesiInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<EmployeeSalary> EmployeeSalaries { get; set; }
        public virtual ICollection<PaySlip> PaySlips { get; set; }
    }
}
